builders:
  dill_to_c:
    import: "package:build_aot/build_aot.dart"
    builder_factories:
      - dillToCBuilder
    build_extensions:
      .dill:
        - .c
    auto_apply: root_package
    applies_builders:
      - build_vm_compilers|entrypoint